### ISSUE TITLE
Migrate to new compiler syntax

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/bazel-feedstock#12]
Looks like this is using C++ code in the `bazel` binary. Would be good to add the new `compiler` syntax here and rebuild.

**Comment by nehaljwani** [comment]
Will have to be careful with this. If new compilers are used, then one will have to statically link the stdlib. See https://github.com/AnacondaRecipes/bazel-feedstock/blob/master/recipe/build.sh

**Comment by nehaljwani** [comment]
That's because bazel unpacks itself an a few other things which depend on libstdc++/libc++ in some temporary directory and these are then invoked from there.

**Comment by jschueller** [comment]
looks like it has been fixed
