### ISSUE TITLE
Syntax errors in bazel-feedstock/recipe/0004-zipper-from-conda-package.patch

### ISSUE THREAD

**Issue by tbenthompson** [conda-forge/bazel-feedstock#121]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When I run a build that requires zipper, I get errors like:
```
ERROR: /.../share/bazel/e995319552096be3cf407df7f1ec2bca/external/bazel_tools/tools/zip/BUILD:11:1: indentation error
ERROR: /.../share/bazel/e995319552096be3cf407df7f1ec2bca/external/bazel_tools/tools/zip/BUILD:14:2: Trailing comma is allowed only in parenthesized tuples.
ERROR: /.../share/bazel/e995319552096be3cf407df7f1ec2bca/external/bazel_tools/tools/zip/BUILD:14:3: syntax error at 'outdent': expected expression
ERROR: /.../share/bazel/e995319552096be3cf407df7f1ec2bca/external/bazel_tools/tools/jdk/BUILD:422:10: every rule of type py_binary implicitly depends upon the target '@bazel_tools//tools/zip:zipper', but this target could not be found because of: no such target '@bazel_tools//tools/zip:zipper': target 'zipper' not declared in package 'tools/zip' defined by /.../share/bazel/e995319552096be3cf407df7f1ec2bca/external/bazel_tools/tools/zip/BUILD
```

The underlying problem is this patch: https://github.com/conda-forge/bazel-feedstock/blob/92df208304035ceacf7024bcccea8351781479ea/recipe/0004-zipper-from-conda-package.patch

```
+ filegroup(
+     name = "zipper",
+    srcs = [":zipper-exec"],
+ )
```

This raises two points:
1. The precise point: **There are syntax errors in the patch that are introducing the errors above.** The space in between "+" and "filegroup" is incorrect. Also the indentation of `name` is one character too deep. Since this is effectively a subdialect of Python, it causes syntax errors as seen above 
2. The broad point: It would be nice to have some kind of CI test suite to ensure that this feedstock for bazel is actually correct. 

### Installed packages

```shell
not relevant
```

### Environment info

```shell
not relevant
```

**Comment by tbenthompson** [comment]
Also, hi @xhochy , thanks for packaging bazel for conda-forge!!! Always bringing magic to the world.

**Comment by xhochy** [comment]
@tbenthompson 👋 We have tests. Every time we build the package, we check that we can compile the tutorial code: https://github.com/conda-forge/bazel-feedstock/blob/b2e499acd0cd26c3ac721c2e329eb1118caaa633/recipe/run_test.sh#L1 This doesn't include anything with `zipper` though.
