### ISSUE TITLE
Incompatibilities with openjdk 17

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/bazel-feedstock#136]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Some projects rely on old versions of Bazel on purpose (e.g. `tensorstore`), as specified in their `.bazelversion` file.

conda-forge has access to openjdk 17 since last week or so, but this openjdk is not compatible with Bazel 5.0 and 5.1 ([ref](https://github.com/bazelbuild/bazel/issues/15531)). The solution for those is to pin `openjdk` to the previous release (`11`) ([source comment](https://github.com/bazelbuild/bazel/issues/15531#issuecomment-1146666693)). 

v5.2 is not affected ([ref](https://github.com/bazelbuild/bazel/issues/14548#issuecomment-1184086950)).

@xhochy - do you think we should issue a repodata patch or is this report enough? [Only `jaxlib` relies on 5.1.1](https://github.com/conda-forge/jaxlib-feedstock/blob/b81dec0dba3a54aef8d8e4e29c8a06a0bc4fd13b/recipe/meta.yaml#L46), but they have an upper bound, so they are getting 5.2, I guess.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by h-vetinari** [comment]
> v5.2 is not affected

Ran into [build errors](https://github.com/conda-forge/bazel-feedstock/pull/138#issuecomment-1215073336) in #138 (targetting main), which had very java-flavoured stacktrace and went away when I restricted to <17, so I'm pretty sure 5.2 is affected.

**Comment by h-vetinari** [comment]
I opened a PR to lift this cap again (now that openjdk 17 is getting way more widespread): #194

**Comment by h-vetinari** [comment]
This has been "fixed" by #236 😄
