### ISSUE TITLE
Do we really need branches for BOTH 4.2.1 & 4.2.x?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/bazel-feedstock#148]
I would have guessed the differences between 4.2.1 & 4.2.2 should be miniscule, but @xhochy seemed to think it necessary to add 4.2.1 https://github.com/conda-forge/bazel-feedstock/commit/04b5cd5cd891be0934b202e979d61a3b92afda03 despite 4.2.x already being present then.

Since we have to rebuild this continuously (abseil & grpc, but also for jdk, see #136), maintaining both branches is IMO quite some effort compared to just patching out a hard requirement on 4.2.1 in a consuming feedstock and replacing it with 4.2.2.

Or what am I missing @conda-forge/bazel?

**Comment by xhochy** [comment]
I think this was needed for `jaxlib` as they have quite a strict bazel version requirement. We can remove it from there as newer jaxlib versions use a newer bazel version.

**Comment by h-vetinari** [comment]
OK, I'll remove it from the abi_migration_branches here.
