### ISSUE TITLE
Retire 4.2.x branch

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/bazel-feedstock#193]
The 4.2.x branch hasn't received an update since last November, and unmerged migrations are piling up. Apparently this isn't causing big problems for anyone, further indicating that 4.2.x is not in use anymore.

Based on a quick code [search](https://github.com/search?q=org%3Aconda-forge%20%2F-%20bazel%2F&type=code), nobody is using 4.2.x on up-to-date feedstocks anymore.

I propose to remove it from the `abi_migration_branches`. Any objections?

@conda-forge/bazel
@conda-forge/jaxlib 
@conda-forge/ray-packages 
@conda-forge/tensorflow

**Comment by mattip** [comment]
+1 for retiring the 4.2 branch from the perspective of ray-packages.
