### ISSUE TITLE
Track upstream fix for Visual Studio 2022+

### ISSUE THREAD

**Issue by mattip** [conda-forge/bazel-feedstock#196]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

bazel has a problem identifying and using Visual Studio 2022+, see https://github.com/bazelbuild/bazel/issues/18592 and the suggested fix in https://github.com/bazelbuild/bazel/pull/18608

### Installed packages

```shell
using any version of bazel
```

### Environment info

```shell
using any version of bazel
```

**Comment by h-vetinari** [comment]
https://github.com/bazelbuild/bazel/pull/18608 has been picked into both main and 5.x already (see https://github.com/conda-forge/bazel-feedstock/pull/188 & https://github.com/conda-forge/bazel-feedstock/pull/189). Are you experiencing failures with the most recent builds nevertheless?

**Comment by mattip** [comment]
Ahh, cool. Sorry for the noise.
