### ISSUE TITLE
Example toolchain configuration for conda-forge compilers

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/bazel-feedstock#45]
I was wondering if any of the `bazel` recipe maintainers have used bazel-3 with conda-forge's compilers.  I don't have any experience with bazel, but I think it would require setting up a custom [C++ toolchain][1].

I notice that the `tensorflow` feedstock uses a [custom clang toolchain][2], but that was written for a fairly old version of bazel.  I tried using it with bazel 3, and ran into an error.

Anyway, if anyone knows what files are required for using `gxx_linux-64` and `clangxx_osx-64` in a bazel project, they would be a great addition to this feedstock, either as examples here in the feedstock source, or maybe even shipped in the built package. (I dunno, somewhere in `${PREFIX}/share` maybe?)

[1]: https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html
[2]: https://github.com/conda-forge/tensorflow-feedstock/tree/master/recipe/custom_clang_toolchain

**Comment by xhochy** [comment]
Working on this in #62
