### ISSUE TITLE
Branch of feedstock for 3.1?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/bazel-feedstock#54]
I'm [trying](https://github.com/conda-forge/tensorflow-feedstock/pull/110) to revive the tensorflow feedstock and push it to 2.4.0, and the build requires a very [specific](https://github.com/tensorflow/tensorflow/blob/v2.4.0/.bazelversion) version, which happens to be 3.1.0

Currently, I'm following the approach of rebuilding bazel itself during the build of tensorflow, but this:
* wastes time (which is relevant because the build is hitting the 6h mark)
* fails on osx
* and is hard with windows

For this reason, I'd be happy if someone from @conda-forge/bazel could create a branch `3.1.x`, and I'd be happy to try raising a PR against that.

**Comment by nehaljwani** [comment]
Resolved via https://github.com/conda-forge/bazel-feedstock/pull/55
